### ISSUE TITLE
Update home page content, and reflect sponsoring parties

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/iso-geodetic-registry#145] opened 2021-08-09 06:46 UTC
Update text to:

---

### ISO Geodetic Registry

The ISO Geodetic Registry is a structured database of coordinate reference systems (CRS) and transformations that is accessible through this online registry system. The Register includes only systems and transformations of international application. It does not include all possible coordinate reference systems and transformations.

This Registry is provided under the auspices of [ISO Technical Committee 211](https://committee.iso.org/home/tc211) on geographic information/geomatics and conforms to ISO standards [ISO 19111:2007](https://www.iso.org/standard/41126.html) (Spatial referencing by coordinates), [ISO 19127:2019](https://www.iso.org/standard/67252.html) (Geodetic register) and [ISO 19135-1:2015](https://www.iso.org/standard/54721.html) (Procedures for item registration -- Part 1: Fundamentals).

### Usage and license

The Registry may be used free of charge but its use is subject to acceptance of the [Terms of Use](https://geodetic.isotc211.org/terms). Use of the Registry implies acceptance of these Terms of Use. Users of the Registry may query and view data and generate reports via anonymous guest access. Users may also submit proposals for new additions or clarifications to the registry.

The Registry also provides a web service interface, allowing geospatial software to query and retrieve information from the Register. Information on using the web services is available in the [Registry user's guide](https://iso-tc211.github.io/iso-geodetic-register-docs/).

### Sponsors and supporters

The ISO Geodetic Register is made available to the public free-of-charge with financial support given by the following sponsors, including:

* [NRCan](https://www.nrcan.gc.ca) 
![image](https://user-images.githubusercontent.com/11865/128666171-6468f5ad-aa32-43da-98ca-47b074de4b55.png)

* [Institut national de l'information géographique et forestière](https://www.ign.fr)
![image](https://user-images.githubusercontent.com/11865/128666318-e8f59cbc-06d9-457d-b38d-c30a8ffb4352.png)

* [Kartverket](https://www.kartverket.no)
![image](https://www.kartverket.no/globalassets/om-kartverket/kartverkslogo/kartverket_liggende_web.svg)

* [Ribose](https://www.ribose.com)
![image](https://github.com/ISO-TC211/jekyll-theme-isotc211/raw/master/assets/logo-ribose.svg)

### Contacting us

If you encounter issues or have any questions about the ISO Geodetic Register, please use the [Feedback](https://geodetic.isotc211.org/feedback) page to submit them. A member of the team will reach out to you directly.

### Registration Authority

Ribose is appointed as Registration Authority of the ISO Geodetic Register by ISO in 2019 in accordance to ISO/TMB resolution 4/2019 and ISO/TC 211 Resolution 912. As Registration Authority, Ribose is responsible for providing registration services for the ISO Geodetic Register in relation to the [ISO 19127](https://www.iso.org/standard/67252.html) International Standard.

**Comment by ronaldtse** [comment] 2021-08-09 06:48
Ping @strogonoff for the corresponding Paneron update.

**Comment by ronaldtse** [comment] 2021-08-11 08:09
Just to double check are you using the correct AWS account number?

**Comment by ronaldtse** [comment] 2021-08-12 13:27
Thanks @strogonoff ! We will also have to tune the message a bit so will let you know when it changes here.

**Comment by ronaldtse** [comment] 2021-08-12 13:58
From @maccraymer 

1. Reorder sections. I think the following order would be more logical in terms of importance to users:
    * ISO Geodetic Registry (ISOGR)
    * Usage and license
    * Registration Authority
    * Contacting us
    * Sponsors
2. Define ISOGR acronym – I suggest to put it immediately after the title “ISO Geodetic Registry (ISOGR)”.
3. Usage and license
    * Need to change statement: “Users may also submit proposals…” to “Only approved authoritative agencies may submit proposals…”
    * Add an additional statement something like “Such agencies need submit their request to submit via the Feedback page.” The feedback mechanism is the only way to get notified of new agencies needing to register. The registration mechanism does not notify anyone of new registration requests (at least in the existing Registry). Hopefully, the new platform will notify the Register Manager via email of any new registration requests.
4. Sponsors
    * Sponsor paragraph and logo images should be at the very bottom of page.
    * Do not hyphenate “free-of-charge”.
    * Replace “financial support given by the following sponsors, including” with “financial support provided by the following sponsors:” (replace “given” with “provided”, remove “including”, and add colon at end).
    * No need to display the name of sponsors in addition to their logos which already includes the names.
    * The sponsor logo images are too large, especially IGN. Make them smaller and of similar size and on the same line. The much larger IGN logo also gives the incorrect impression IGN has sponsored the most while it actually contributed the least by an order of magnitude. I suggest to put the sponsor images in order of magnitude of contribution: Ribose, Karverket, NRCan, IGN.
5. Last line of the page is hidden by the bottom footer

**Comment by ronaldtse** [comment] 2021-08-12 14:17
Revised text.

-------

### ISO Geodetic Registry (ISOGR)

The ISO Geodetic Registry is a structured database of coordinate reference systems (CRS) and transformations that is accessible through this online registry system. The Register includes only systems and transformations of international application. It does not include all possible coordinate reference systems and transformations.

This Registry is provided under the auspices of [ISO Technical Committee 211](https://committee.iso.org/home/tc211) on geographic information/geomatics and conforms to ISO standards [ISO 19111:2007](https://www.iso.org/standard/41126.html) (Spatial referencing by coordinates), [ISO 19127:2019](https://www.iso.org/standard/67252.html) (Geodetic register) and [ISO 19135-1:2015](https://www.iso.org/standard/54721.html) (Procedures for item registration -- Part 1: Fundamentals).

### Usage and license

The Registry may be used free of charge but its use is subject to acceptance of the [Terms of Use](https://geodetic.isotc211.org/terms). Use of the Registry implies acceptance of these Terms of Use.

* Users of the Registry may query and view data and generate reports via anonymous guest access.
* Only approved authoritative agencies may submit proposals for new additions or clarifications to the registry. Such agencies need submit their request to submit via the Feedback page.
* The Registry also provides a web service interface, allowing geospatial software to query and retrieve information from the Register. Information on using the web services is available in the [Registry user's guide](https://iso-tc211.github.io/iso-geodetic-register-docs/).

### Registration Authority

Ribose is appointed as Registration Authority of the ISO Geodetic Register by ISO in 2019 in accordance to ISO/TMB resolution 4/2019 and ISO/TC 211 Resolution 912. As Registration Authority, Ribose is responsible for providing registration services for the ISO Geodetic Register in relation to the [ISO 19127](https://www.iso.org/standard/67252.html) International Standard.

### Contacting us

If you encounter issues or have any questions about the ISO Geodetic Register, please use the [Feedback](https://geodetic.isotc211.org/feedback) page to submit them. A member of the team will reach out to you directly.

### Sponsors

The ISO Geodetic Register is made available to the public free of charge with financial support provided by the following sponsors:

* [Ribose](https://www.ribose.com)
![image](https://github.com/ISO-TC211/jekyll-theme-isotc211/raw/master/assets/logo-ribose.svg)

* [Kartverket](https://www.kartverket.no)
![image](https://www.kartverket.no/globalassets/om-kartverket/kartverkslogo/kartverket_liggende_web.svg)

* [NRCan](https://www.nrcan.gc.ca) 
![image](https://user-images.githubusercontent.com/11865/128666171-6468f5ad-aa32-43da-98ca-47b074de4b55.png)

* [Institut national de l'information géographique et forestière](https://www.ign.fr)
![image](https://user-images.githubusercontent.com/11865/128666318-e8f59cbc-06d9-457d-b38d-c30a8ffb4352.png)

**Comment by ronaldtse** [comment] 2021-08-13 01:52
@phuonghuynh @strogonoff can you let me know once this change is done? Thanks.

P.S. please keep in mind @maccraymer 's feedback of:
> The sponsor logo images are too large, especially IGN. Make them smaller and of similar size and on the same line. The much larger IGN logo also gives the incorrect impression IGN has sponsored the most while it actually contributed the least by an order of magnitude. I suggest to put the sponsor images in order of magnitude of contribution: Ribose, Karverket, NRCan, IGN.

**Comment by strogonoff** [comment] 2021-08-13 03:58
Reducing the size any further will make the text on two of the four logos illegible.

**Comment by ronaldtse** [comment] 2021-08-13 04:17
@strogonoff the Paneron site does not have the problem about logo size, but please help update the order of logos. Thanks.

**Comment by maccraymer** [comment] 2021-08-13 14:38
Not sure if I can reply to this GitHub issue via email reply but here goes…

It is really just the IGN logo that needs to be scaled down and it has large fonts so it will still be legible.

The Kartverket & Ribose logos also have fairly large fonts and can be scaled down a bit as well, if needed.

The NRCan logo is actually two logos: the top NRCan logo with the small text and the bottom Gov’t of Canada logo. You can get rid of the bottom Canada logo. And I can provide a smaller (width-wise) NRCan logo that you won’t have to shrink (or at least not too much). All I will do is shift the English and French text closer to each other and to the flag. I can also try resizing the vertical dimension larger if shrinking the horizontal. That will help make the text more legible. I do this all the time with our logo because it is so wide with both official languages.

The other logos can be scaled down (if needed) to roughly the size of the NRCan logo. I’m not sure if they will all fit on one line. If not, hopefully, they will not require as much vertical space as now if they are on two lines.

I will try preparing a mock up on a generic web page for an example.

Thanks,
-Mike

Sent from my iPhone with autocorrect typos

On Aug 12, 2021, at 11:58 PM, Anton Strogonoff ***@***.***> wrote:

﻿

Reducing the size any further will make the text on two of the four logos illegible.

> On 13 Aug 2021, at 8:53 AM, Ronald Tse ***@***.***> wrote:
>
> ﻿
> @phuonghuynh @strogonoff can you let me know once this change is done? Thanks.
>
> P.S. please keep in mind @maccraymer 's feedback of:
>
> The sponsor logo images are too large, especially IGN. Make them smaller and of similar size and on the same line. The much larger IGN logo also gives the incorrect impression IGN has sponsored the most while it actually contributed the least by an order of magnitude. I suggest to put the sponsor images in order of magnitude of contribution: Ribose, Karverket, NRCan, IGN.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FISO-TC211%2Fiso-geodetic-registry%2Fissues%2F145%23issuecomment-898173488&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb2bac777ad924bc2b02c08d95e0e9c4d%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644239124492861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ySPnihM0ruyWkOBNv80PNcLCT7dQaroQhGshLgOOl1Y%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGURRKI5NC53SJ2Y3XLBUSLT4SJ55ANCNFSM5BZMKUDQ&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb2bac777ad924bc2b02c08d95e0e9c4d%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644239124502860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZDlGMAba5DGaEFdT5H7rBqtzAQZB7fI1EMYk6e9DiYA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb2bac777ad924bc2b02c08d95e0e9c4d%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644239124502860%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gN8kGYO0nTqkbKefDPeQYGURWF6zMNeyUBXjFF0tjQs%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7Cb2bac777ad924bc2b02c08d95e0e9c4d%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644239124512855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O7q23jK%2BFwjPaCVvMDjxsho4kwZDhhkjpMi2E8QlYUc%3D&reserved=0>.

**Comment by phuonghuynh** [comment] 2021-08-13 14:47
For the "geodetic.isotc211.org" ; some logos have been scale down to 50%

**Comment by maccraymer** [comment] 2021-08-13 15:12
The logos size is better on the Paneron site. You should get rid of the “Canada” part of the NRCan logo which will then allow you to enlarge the NRCan part to make it more legible. I will also provide a new NRCan logo with the English and French text closer together and closer to the flag so it’s not so wide when enlarged.

I also think the logos in Paneron should be side-by-side so they don’t take up as much vertical space.

BTW, I’m not a fan of the single-level vertical stacking of text boxes for all information on the Paneron home page. I assume this is done just for development purposes and the final home page will have something more structured to show the hierarchy of information. Similar to the current registry.

Is it also possible to have a navigation panel on the left like the current registry? It would always show the hierarchy of the information and allow for quicker navigation between different parts of the hierarchy. I rather like the current GUI in that respect. As a user of the registry, I find it very easy and efficient to use.

Rather than having the user click a “Browse” hyperlink button to display the items for each item class, I think it would be more efficient (and require less space) to make the entire text box a hyperlink. It’s easier and faster to aim my cursor or finger at the entire box than the smaller browse button. Or maybe this is irrelevant if the home page is just temporary for development.

Finally, I assume there will eventually be a search function but have you given any thought yet as to how it might function? I rather like the real-time (immediate) functionality of the one in the current registry. The problem is it only searches the item number and name field. By default it should also search the alias field. And of course it should have an “advanced” option to select other fields to search. I’m sure you’ve already thought about all this but thought I’d offer my 2 cents anyway.

Aside: The Paneron home page does not render properly on my iPhone in portrait orientation. It’s okay in landscape. Or maybe this is all moot if the home page design is just temporary for development.

Thanks,
-Mike

Sent from my iPhone with autocorrect typos

On Aug 13, 2021, at 12:17 AM, Ronald Tse ***@***.***> wrote:

﻿

@strogonoff<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstrogonoff&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C4150896bd8eb4ad2290308d95e1149ce%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644250612244988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p4FK7p7fUr9v%2FVRA0NcwZ7hQvuCzcVKi%2BN0HIjfqehE%3D&reserved=0> the Paneron site does not have the problem about logo size, but please help update the order of logos. Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FISO-TC211%2Fiso-geodetic-registry%2Fissues%2F145%23issuecomment-898179637&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C4150896bd8eb4ad2290308d95e1149ce%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644250612254982%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rENoTJf%2FjTDgP8Nv6iRoIhAiIO%2F%2FgC0LqZBsZf3%2Bdiw%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGURRKOPN52MC3QNFM4234LT4SMF5ANCNFSM5BZMKUDQ&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C4150896bd8eb4ad2290308d95e1149ce%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644250612254982%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O6z70bqa%2Fy4o4INRuZgTeERp0FGlO07Ak%2B7LgEJfpg4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C4150896bd8eb4ad2290308d95e1149ce%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644250612264975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aSIpcrsSCiwQPKTiZ8wfTMwIzzIJjc%2Fmdx8o3vodVb4%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C4150896bd8eb4ad2290308d95e1149ce%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637644250612264975%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Djma2HS%2B7uDECyHj%2Fc7A397yfIyoQIYFNuZryB21owo%3D&reserved=0>.

**Comment by mcraymer** [comment] 2021-08-16 04:21
I've attached a revised NRCan logo without the Canada word mark and with a slightly compressed width. Please use this one.

[nrcan_logo](https://user-images.githubusercontent.com/20247841/129509749-b4284e9b-359b-49eb-8b50-cfa73871fd70.png)

I've also revised the home page contents per my suggestions above. In addition, I listed the standards the Registry follows in point form. I've attached an index_mc.html file containing these revisions along with the scaled down logos. You can also see it at [https://www.naref.org/isogr/index_mc.html](url).

[index_mc.html.zip](https://github.com/ISO-TC211/iso-geodetic-registry/files/6989689/index_mc.html.zip)

-MIke

**Comment by mcraymer** [comment] 2021-08-16 04:23
Not sure why the link to the naref.org page isn't specified properly. Trying again...
https://www.naref.org/isogr/index_mc.html.

**Comment by mcraymer** [comment] 2021-08-16 04:25
Trying one more time...it's not an https link, it's a plain http link...
http://www.naref.org/isogr/index_mc.html

**Comment by ronaldtse** [comment] 2021-08-16 07:43
@mcraymer right now the size of logos on the mockup show IGN as most prominent. While it is not super important we probably need some thinking here... A "grid" like structure probably works best.

<img width="774" alt="Screenshot 2021-08-16 at 3 34 07 PM" src="https://user-images.githubusercontent.com/11865/129527574-d93fa20d-16d9-4354-b3a4-1453431e2771.png">

**Comment by ronaldtse** [comment] 2021-08-16 07:44
P.S. I've added vector logos for all sponsors here: https://github.com/isogr/brand-assets .

I was able to find an NRCan SVG file which I've fixed up the layout according to your image, so the graphic is more crisp and scalable.

**Comment by maccraymer** [comment] 2021-08-16 11:38
Yes, like Anton said, the IGN text becomes illegible when reducing much further. Unfortunately, they have a huge acronym with their name spelled out in tiny text. I don’t think there’s anything we can do about it unless we just use the IGN acronym without the full name, or vice versa.
-Mike

Sent from my iPhone with autocorrect typos

On Aug 16, 2021, at 3:43 AM, Ronald Tse ***@***.***> wrote:

﻿

@mcraymer<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcraymer&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C5cf579c7865d414c158f08d960898efa%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966203027217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=94c9brtbCbY5OJXTnC%2BJSaTHJPZhtMwvz7pDmAUCD08%3D&reserved=0> right now the size of logos on the mockup show IGN as most prominent. While it is not super important we probably need some thinking here... A "grid" like structure probably works best.

[Screenshot 2021-08-16 at 3 34 07 PM]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11865%2F129527574-d93fa20d-16d9-4354-b3a4-1453431e2771.png&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C5cf579c7865d414c158f08d960898efa%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966203037215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K3R6DcK40z2Epr61Czm%2FrK60G7EGYDXeDvXFZnJprIE%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FISO-TC211%2Fiso-geodetic-registry%2Fissues%2F145%23issuecomment-899295676&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C5cf579c7865d414c158f08d960898efa%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966203047205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pG9EGM4wrjrUN6YK0mPtMu9d0OxqiusXoj%2FZXP%2FC864%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGURRKMRXMVZ6UMB4XIG77TT5C6SDANCNFSM5BZMKUDQ&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C5cf579c7865d414c158f08d960898efa%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966203047205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8skUHT7wHM7B6d6Xms07uSRl8vb90OFX1a5qXyxgCB4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C5cf579c7865d414c158f08d960898efa%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966203057198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f%2FYrTyAL8o%2F6xhKq%2BxEUBnO3PuixNKpsuc0uj0zjAlE%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C5cf579c7865d414c158f08d960898efa%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966203057198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rz4%2FJHG4HqC21YIMK5YHk85Empc8%2BTvE3sLOgl1YZrc%3D&reserved=0>.

**Comment by maccraymer** [comment] 2021-08-16 11:44
The link to all the vector logos didn’t work for me. I get a 404 error.

I’m curious, where did you find the svg image for NRCan? On our website somewhere?

-Mike

Sent from my iPhone with autocorrect typos

On Aug 16, 2021, at 3:44 AM, Ronald Tse ***@***.***> wrote:

P.S. I've added vector logos for all sponsors here: https://github.com/isogr/brand-assets<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fisogr%2Fbrand-assets&data=04%7C01%7Cmichael.craymer%40NRCan-RNCan.gc.ca%7C14cdacee6a7e4bbfb77308d96089bf21%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637646966997304489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cO7KV883mwMm0%2F5z94mcjc9zAlyCPxfqApiDJiXW8nE%3D&reserved=0> . I was able to find an NRCan SVG file which I've fixed up the layout according to your image, so the graphic is more crisp and scalable.

**Comment by ronaldtse** [comment] 2021-08-16 13:10
@maccraymer you have access to the org now at https://github.com/isogr . 

I found it with a query "natural resources canada filetype:svg" on Google Images, one of them is this:
https://windfallcentre.ca/benchmarking/site/gallery_190919/images/logos/NaturalResourcesCanada.svg

**Comment by maccraymer** [comment] 2021-08-30 04:27
Can someone please update the current Registry home page as soon as possible using the text from the following web page:
https://www.naref.org/isogr/index.html.

There are some things that need to be corrected right away. I've also made a few more revisions to the text, including:

* As the CB discussion at its last meeting, I added a paragraph to the end of the first ISOGR section saying that work is underway to upgrade to the new 19111:2019 standard.
* Capitalized Registry at end of 2nd sentence in second paragraph of Usage & license section.
* Removed the paragraph on web services in Usage & license section. Although web services are apparently available, there is no documentation on it in the user guide as stated. I think it's better we not explicitly mention this so we don't get inquiries about it.
* Corrected grammar in Registration Authority paragraph.

The logo scaling in the example web page seems to work well. I've used a Table structure for them.

Thanks,
-Mike

**Comment by ronaldtse** [comment] 2021-08-30 04:30
@phuonghuynh can you help do this today? Thanks.

**Comment by ronaldtse** [comment] 2021-08-30 05:53
@phuonghuynh is on it.

**Comment by phuonghuynh** [comment] 2021-08-30 06:05
@ronaldtse https://www.naref.org/isogr/index.html is 404 to me

**Comment by phuonghuynh** [comment] 2021-08-30 06:17
> Corrected grammar in Registration Authority paragraph.

@ronaldtse do you have the corrected version? ATM the paragraph is

> Registration Authority
> Ribose is appointed as Registration Authority of the ISO Geodetic Register by ISO in 2019 in accordance to ISO/TMB resolution 4/2019 and ISO/TC 211 Resolution 912. As Registration Authority, Ribose is responsible for providing registration services for the ISO Geodetic Register in relation to the ISO 19127 International Standard.

**Comment by phuonghuynh** [comment] 2021-08-30 06:20
Listed items from https://github.com/ISO-TC211/iso-geodetic-registry/issues/145#issuecomment-908014589

- [ ] As the CB discussion at its last meeting, I added a paragraph to the end of the first ISOGR section saying that work is underway to upgrade to the new 19111:2019 standard.
- [x] Capitalized Registry at end of 2nd sentence in second paragraph of Usage & license section.
- [x] Removed the paragraph on web services in Usage & license section. Although web services are apparently available, there is no documentation on it in the user guide as stated. I think it's better we not explicitly mention this so we don't get inquiries about it.
- [ ] Corrected grammar in Registration Authority paragraph.

**Comment by ronaldtse** [comment] 2021-08-30 06:59
@phuonghuynh try this, it works
http://www.naref.org/isogr/index.html

**Comment by maccraymer** [comment] 2021-08-30 09:55
Sorry for using https in the URL of the example. As Ron realized, it is actually just http. I see the home page has already been updated. Thanks guys for doing this so quickly!! Greatly appreciated!

**Comment by phuonghuynh** [comment] 2021-08-30 10:09
Close this as comment in https://github.com/ISO-TC211/iso-geodetic-registry/issues/145#issuecomment-908207103

**Closed by phuonghuynh** 2021-08-30 10:09 UTC
Labels: enhancement

**Comment by ronaldtse** [comment] 2021-08-30 11:44
Thank you @maccraymer @phuonghuynh !!
